//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "games")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub player1: String,
    pub player2: String,
    pub mode: i32,
    pub length: i32,
    pub player1_score: i32,
    pub player2_score: i32,
    pub winner: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sets::Entity")]
    Sets,
    #[sea_orm(has_many = "super::throws::Entity")]
    Throws,
}

impl Related<super::sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sets.def()
    }
}

impl Related<super::throws::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Throws.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
