//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "games")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub player1: String,
    pub player2: String,
    pub mode: i32,
    pub sets: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::throws::Entity")]
    Throws,
}

impl Related<super::throws::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Throws.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
