//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rounds")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub number: i32,
    pub leg_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::legs::Entity",
        from = "Column::LegId",
        to = "super::legs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Legs,
    #[sea_orm(has_many = "super::throws::Entity")]
    Throws,
}

impl Related<super::legs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Legs.def()
    }
}

impl Related<super::throws::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Throws.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
