name: dart-backend
services:
  dart-backend:
    container_name: dart-backend
    image: dart-backend
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    volumes:
      - ../:/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - dart-backend
    depends_on:
      - dart-db

  dart-db:
    container_name: dart_db
    hostname: dart_db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ../database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: dart
      PGPORT: 5432
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - dart-backend

networks:
  dart-backend:
    name: dart-backend
    driver: bridge
